language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - 5.6
    - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - mv composer.phar composer
  - ./composer install --dev

script: ./vendor/bin/phpunit tests
